name: Buildroot Prebuilt Container

on: workflow_dispatch

jobs:
  buildroot-container:
    name: "Build Buildroot Prebuilt Container"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Container
      run: |
        docker build UET/Lib/Container/rkm-initrd-builder -f prebuilt.Dockerfile --tag ghcr.io/redpointgames/uet/buildroot-prebuilt-base:latest
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Container
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/redpointgames/uet/buildroot-prebuilt-base:latest
